### ISSUE TITLE
deserialize?

### ISSUE THREAD

**Issue by Meekohi** [hongymagic/jQuery.serializeObject#12]
Anyone have nice tricks for deserializing an object back to a form (i.e. if you want to edit the object it later).

**Comment by hongymagic** [comment]
Something like:

1. http://jquery-load-json.googlecode.com/svn/trunk/edit.html?ID=19
2. http://stackoverflow.com/questions/7347580/bind-json-properties-to-a-form

Deserialising JSON into any form is not the responsibility of this plugin.
