### ISSUE TITLE
Json one single value to multidimension array

### ISSUE THREAD

**Issue by sondang86** [hongymagic/jQuery.serializeObject#15]
Hello,

Is there any other way to convert from one single value to array? for example, I have below single object:
1st:
 Object { js_language="1",  js_language_level="1"}

and this is two values object:
2st:
 Object { js_language=[2],  js_language_level=[2]}

what I wanted is convert 1st from :
 Object { js_language="1",  js_language_level="1"}

to 

 Object { js_language=[1],  js_language_level=[1]}

Are there any way to achieve it with serializeObject?

Thanks in advanced

**Comment by hongymagic** [comment]
No, that won't be supported. This plugin is a mirror of `$.serialize() and $.serializeArray()`. You can convert to that model after running `$.serializeObject`.
